### ISSUE TITLE
ENH Add support for project.toml

### ISSUE THREAD

**Issue by s-weigand** [nbQA-dev/nbQA#211]
See discussion in #210 

A possible example, [corresponding to the docs](https://nbqa.readthedocs.io/en/latest/configuration.html) would be:
```toml
[tool.nbqa.mutate]
black = true
isort = false

[tool.nbqa.addopts]
flake8 = [
    "--ignore W503",
    ]

[tool.nbqa.configs]
mypy = ".mypy.ini"
```
