### ISSUE TITLE
ENH Add pre-commit hooks for supported tools to .pre-commit-hooks.yaml

### ISSUE THREAD

**Issue by s-weigand** [nbQA-dev/nbQA#260]
Baiscally, this is how [pre-commit-hooks](https://github.com/pre-commit/pre-commit-hooks/blob/master/.pre-commit-hooks.yaml) does it.
This would allow to make the `.pre-commit-config.yaml` syntax a lot more concise.

Using:

```yaml
- repo: https://github.com/nbQA-dev/nbQA
  rev: 0.1.x
  hooks:
    - id: nbqa-flake8
    - id: nbqa-isort
```

Instead of:

```yaml
- repo: https://github.com/nbQA-dev/nbQA
  rev: 0.1.32
  hooks:
    - id: nbqa
      args: ["flake8"]
      name: nbqa-flake8
      alias: nbqa-flake8
      additional_dependencies: ["flake8"]
    - id: nbqa
      args: ["isort", "--nbqa-mutate"]
      name: nbqa-isort
      alias: nbqa-isort
      additional_dependencies: ["isort"]
```

Didn't test if it works, just leaving the idea here.
If adding the `args` to the `entry` doesn't work, we could always add additional entry points in `setup.py`.
