### ISSUE TITLE
Make a GitHub action

### ISSUE THREAD

**Issue by MarcoGorelli** [nbQA-dev/nbQA#428]
similar to what they do here https://github.com/psf/black#github-actions

**Comment by neomatrix369** [comment]
I was going to suggest this as well, its not hard to create a GH actually I have done one in the past

**Comment by s-weigand** [comment]
I have a [template for actions](https://github.com/s-weigand/github-action-template) which includes a workflow to publish major version tags on release.
So the hardest part is to come up with a usage scheme.
E.g.
```yaml
  - uses:  nbQA-dev/nbQA-action@v1
    with:
      tool: black
```
or rather

```yaml
  - uses:  nbQA-dev/nbQA-action@v1
    with:
      tools: [black, flake8, ...]
```
