### ISSUE TITLE
nbqa-mypy output doesn't preserve colour

### ISSUE THREAD

**Issue by ravwojdyla** [nbQA-dev/nbQA#551]
nbqa-mypy output doesn't colour the output, making it harder to read the errors. Is this expected?

My config:

```
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 0.5.9
    hooks:
      - id: nbqa-mypy
        args: ["--strict", "--show-error-codes", "--pretty", "--show-error-context", "--color-output"]
```

The `--color-output` (which afaiu is the default) is likely "ignored" because at the time of the execution there's no tty (is this how nbqa executes mypy?). Related mypy issue: https://github.com/python/mypy/issues/7771

This can be workaround with a hidden force color flag, example:

```cli
> MYPY_FORCE_COLOR=1 pre-commit run nbqa-mypy
```
