### ISSUE TITLE
notebook shadow module causing mypy errors

### ISSUE THREAD

**Issue by ravwojdyla** [nbQA-dev/nbQA#556]
When a package contains both notebook and a module with the same exact name, it seems like nbqa-mypy gets confused and the notebook shadows the module causing mypy errors.

Example structure:

```
pipelines/foo
├── __init__.py
├── bar.py
├── bar.ipynb
```

My config:

```yaml
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 0.5.9
    hooks:
      - id: nbqa-mypy
        args: ["--nbqa-ignore-cells=%%R,%%bash", "--strict", "--show-error-codes", "--pretty", "--show-error-context"]
```
