### ISSUE TITLE
Autopep8 corrupting notebooks with !pip command

### ISSUE THREAD

**Issue by subpath** [nbQA-dev/nbQA#696]
autopep8 changing order of import and `!pip install` command so notebook became corrupted because I want my `!pip install` command to be the first cell in the notebook. 

Is there some parameter that I can use with autopep8 to avoid it?

Cheers : ) 

### Steps to recreate
before:
```
# cell 1
!pip install -q pandas
# cell 2
import pandas as pd
```

after:
```
# cell 1
import pandas as pd
!pip install -q pandas
```

pre-commit-config.yaml
```yaml
repos:
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.2.2
    hooks:
      - id: nbqa-autopep8
```
