### ISSUE TITLE
Pre-commit hook 

### ISSUE THREAD

**Issue by ncgoodbody** [nbQA-dev/nbQA#713]
Hello! First off, I love this tool. I'm leading a team of curriculum developers, and we use`nbqa-isort` and `nbqa-black` to keep all our code consistent. It's a lifesaver, so thank you for putting it out into the world. 

I'm having an issue with `nbqa-isort` where I can't pass the pre-commit hook even when changes have been made to the file. 

For example, I'll have a cell of imports at the top of `foo.ipynb`

<img width="1047" alt="Screen Shot 2022-03-15 at 3 10 12 PM" src="https://user-images.githubusercontent.com/16094430/158480846-80d692a6-583f-4cdf-b46c-8da9e160c7cf.png">

 I'll commit my code and get this message:

```bash
nbqa-isort...............................................................Failed
- hook id: nbqa-isort
- files were modified by this hook

Fixing file.ipynb
```

The imports will be fixed:

<img width="1046" alt="Screen Shot 2022-03-15 at 3 05 26 PM" src="https://user-images.githubusercontent.com/16094430/158480325-50eab16d-9269-46ce-9529-b4cd9456f4f0.png">

But then when I try to commit the corrected file, I get the same fail message

```bash
nbqa-isort...............................................................Failed
- hook id: nbqa-isort
- files were modified by this hook

Fixing file.ipynb
```

So I end up stuck in a loop where the file is fixed, but I still can't commit it. 

Is there something I'm missing? Something in the cell that's throwing off `nbqa-isort`? Would love some guidance. 

Here's what my `.pre-commit-config.yaml` looks like:

```yaml
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.3.1
  hooks:
  - id: nbqa-isort
    args: [--nbqa-exclude=^old_curriculum/]
  - id: nbqa-black
    args: [--nbqa-exclude=^old_curriculum/]
  - id: nbqa-flake8
    args: ['--ignore=E501,E402,W503', --nbqa-exclude=^old_curriculum/]
```

I'm running MacOS (Big Sur v. 11.6.4 (20G417))
