### ISSUE TITLE
Can't pass args to `nbqa flake8` through `pre-commit`

### ISSUE THREAD

**Issue by janosh** [nbQA-dev/nbQA#731]
Pasting this snippet into `.pre-commit-config.yaml`

```yml
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.3.1
    hooks:
      - id: nbqa-flake8
        args: [--ignore, E402]
```

and running

```sh
pre-commit run nbqa-flake8 --files examples/*.ipynb
```

raises

```sh
nbqa-flake8..............................................................Failed
- hook id: nbqa-flake8
- exit code: 1

No such file or directory: E402
```

which arises because it translates to this command

```sh
nbqa flake8 --ignore E402 examples/*.ipynb
```

whereas `flake8` requires

```sh
nbqa flake8 examples/*.ipynb --ignore E402
```
