### ISSUE TITLE
New pre-commit hook for autoflake

### ISSUE THREAD

**Issue by hofbi** [nbQA-dev/nbQA#755]
Great collection of tools for notebooks. It would be great if you could add a pre-commit hook for https://github.com/PyCQA/autoflake

**Comment by MarcoGorelli** [comment]
Hey @hofbi 

I'm not 100% confident about including `autoflake`, because imports might be used in parts of the notebook that nbqa can't currently process, see https://nbqa.readthedocs.io/en/latest/known-limitations.html

Having said that, you can already make a hook yourself to use autoflake:
```
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.5.2
  hooks:
    - id: nbqa
      entry: nbqa autoflake -i
      name: nbqa-autoflake
      alias: nbqa-autoflake
      additional_dependencies: [autoflake==<version number>]  # put which version of autoflake you want here
```
