### ISSUE TITLE
add-trailing-comma

### ISSUE THREAD

**Issue by MarcoGorelli** [nbQA-dev/nbQA#759]
@cyyc1 just FYI you can use nbqa to run `add-trailing-comma` on notebooks

https://github.com/asottile/add-trailing-comma/issues/204

**Comment by cyyc1** [comment]
Hi @MarcoGorelli , thank you for tagging me here. I know of nbQA but I am not seeing an option to use add-training-comma with nbQA.

Could you show me an example? I'm in particular interested in using in in pre-commit.

Thanks.

**Comment by MarcoGorelli** [comment]
Hey @cyyc1 

sure, here you go:
```
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.5.2
  hooks:
    - id: nbqa
      entry: nbqa add-trailing-comma
      name: nbqa-add-trailing-comma
      alias: nbqa-add-trailing-comma
      additional_dependencies: [add-trailing-comma==v2.3.0]
```

Does this work for you?

**Comment by cyyc1** [comment]
I tried your suggestion, and saw the following message:

```
[ERROR] `nbqa-add-trailing-comma` is not present in repository https://github.com/nbQA-dev/nbQA.  Typo? Perhaps it is introduced in a newer version?  Often `pre-commit autoupdate` fixes this.
```

I ran `pre-commit autoupdate` and here's the message I saw:

```
Updating https://github.com/nbQA-dev/nbQA ... Cannot update because the update target is missing these hooks:
nbqa-add-trailing-comma
```

**Comment by MarcoGorelli** [comment]
oops, I should've tried it before suggesting it, sorry, `id` should just be `nbqa`
```
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.5.2
  hooks:
    - id: nbqa
      entry: nbqa add-trailing-comma
      name: nbqa-add-trailing-comma
      alias: nbqa-add-trailing-comma
      additional_dependencies: [add-trailing-comma==v2.3.0]
```
```

**Comment by MarcoGorelli** [comment]
got it, just updated my comment, works for me now:
```
(base) marcogorelli@DESKTOP-U8OKFP3:~/tmp$ pre-commit run -a
nbqa-add-trailing-comma..................................................Passed
(base) marcogorelli@DESKTOP-U8OKFP3:~/tmp$ cat .pre-commit-config.yaml
repos:
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.5.2
  hooks:
    - id: nbqa
      entry: nbqa add_trailing_comma
      name: nbqa-add-trailing-comma
      alias: nbqa-add-trailing-comma
      additional_dependencies: [add-trailing-comma==2.3.0]
```
