### ISSUE TITLE
Useful tool for nbQA: docformatter

### ISSUE THREAD

**Issue by tovrstra** [nbQA-dev/nbQA#765]
The following works with nbQA (1.5.2) and [docformatter](https://github.com/PyCQA/docformatter) (1.5.0).

```bash
nbqa docformatter -i example.ipynb
```

The `-i` option is needed to tell docformatter to modify the notebook in-place.

For those using pre-commit, the following configuration can be used:

```yaml
repos:
- repo: https://github.com/nbQA-dev/nbQA
  rev: "1.5.2"
  hooks:
    - id: nbqa
      entry: nbqa docformatter -i
      name: nbqa-docformatter
      alias: nbqa-docformatter
      additional_dependencies: [docformatter==1.5.0]
```

It might be useful to support docformatter out of the box in nbQA, or to show this example in the documentation. (The documentation already explains how to get custom tools to work, but a working example is always nice to have.)

Here is an example notebook to try out the above setup: [example_nbqa_docformatter.zip](https://github.com/nbQA-dev/nbQA/files/9819497/example_nbqa_docformatter.zip)
