### ISSUE TITLE
Support flake8 configured through pyproject.toml

### ISSUE THREAD

**Issue by thatneat** [nbQA-dev/nbQA#776]
Most tools have been converging towards having their configuration live in `pyproject.toml` but the core `flake8` has not yet done so.

`flake8-pyproject` is a variant of flake8 that supports configuration through `pyproject.toml`. Is there a way to enable that with your tool or precommit hook so that those of us configuring flake8 through `pyproject.toml` can get the benefits of configuring `nbqa-flake8`? 

Right now, workarounds include moving my config to `setup.cfg` or duplicating the important config as command-line arguments.

**Comment by s-weigand** [comment]
Does adding it as an additional dependency not work?
```yaml
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.5.3
  hooks:
    - id: nbqa-flake8
      additional_dependencies: [flake8, flake8-pyproject] 
```
From [the project itself](https://github.com/john-hen/Flake8-pyproject), it seems to me that it should `just work` like this
