### ISSUE TITLE
pre-commit hooks don't see installed packages

### ISSUE THREAD

**Issue by l0b0** [nbQA-dev/nbQA#788]
I'm trying to get the following configuration to work in a [repo](https://github.com/linz/emergency-management-tools/):

```
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 73e47d5a94b8724ce0b36e7bf29103a6f45dc505 # frozen: 1.6.1
    hooks:
      - id: nbqa-mypy
      - id: nbqa-pylint
```

When running `pre-commit run --all-files`, both of these tools complain about not being able to see the dependencies installed in the current environment. For example, from `mypy`:

```text
[…].ipynb:cell_12:1: error: Cannot find implementation or library stub for module named "geopandas"
```

And from `pylint`:

```text
[…].ipynb:cell_1:9:0: E0401: Unable to import 'numpy' (import-error)
```

But both `python <<< 'import geopandas'` and `python <<< 'import numpy'` know about the modules.
