### ISSUE TITLE
`nbqa-ruff` appears to ignore `per-file-ignores` in `pyproject.toml`

### ISSUE THREAD

**Issue by paddyroddy** [nbQA-dev/nbQA#823]
I'm running the `nbqa-ruff` hook on a notebook which has some `print` and `assert` statements. From `per-file-ignores` these should be ignored, yet they are not. If I move those same rules into `ignore` then it works fine. Is there a reason why `per-file-ignores` isn't respected?

`.pre-commit-config.yaml`
```yaml
repos:
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
      - id: nbqa-ruff
```

`pyproject.toml`
```toml
[tool.ruff]
fix = true
force-exclude = true
per-file-ignores = {"*.ipynb" = [
    "S101",
    "T201",
]}
select = [
    "S",
    "T",
]
```
