### ISSUE TITLE
nbqa-pyupgrade fails on f-string with curly brace

### ISSUE THREAD

**Issue by christian-steinmeyer** [nbQA-dev/nbQA#857]
I'm using this pre-commit config:
```
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.5
    hooks:
      - id: nbqa-pyupgrade
        args: ["--py310-plus"]
```

and get a failed hook on a notebook cell with this content:
```py
sql = f"""
  SELECT
      A,
      B,
      `SOME_ÜMLAUT`
  FROM MY_TABLE
    WHERE `SOME_ÜMLAUT` >= '{SOME_VARIABLE}'
""" 
```

where it autofixes the last line to `WHERE `SOME_ÜMLAUT` >= '{{SOME_VARIABLE}'

Pyupgrade (@  v3.16.0) itself doesn't have this issue, when run on an equivalent python file.
