### ISSUE TITLE
Error with nbqa-ruff hook

### ISSUE THREAD

**Issue by Anu-Ra-g** [nbQA-dev/nbQA#861]
I'm getting an error, while running this hook 
```
- repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
      - id: nbqa-ruff
        args: ["--fix", "--ignore=E402"]
      - id: nbqa-isort
        args: ["--profile=black"]
        additional_dependencies: [isort==5.6.4]
      - id: nbqa-black
      - id: nbqa-pyupgrade
        args: ["--py37-plus"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.243"
    hooks:
      - id: ruff
        args: ["--fix"]
```
I'm getting, 
```
nbqa-ruff................................................................Failed
- hook id: nbqa-ruff
- exit code: 1

error: `ruff <path>` has been removed. Use `ruff check <path>` instead.
```
With the `check` argument, I'm getting this,
```
nbqa-ruff................................................................Failed
- hook id: nbqa-ruff
- exit code: 1

No such file or directory: check
```
I guess this is happening due to lack of support for the new version of `ruff`?
