### ISSUE TITLE
pre-commit autoupdate not finding ruff hooks

### ISSUE THREAD

**Issue by AlinderS** [nbQA-dev/nbQA#867]
I am using the new Ruff hooks. This is the entry in my `.pre-commit-config.yaml`.
```
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.9.0
  hooks:
    - id: nbqa-ruff-check
      args: ["--fix", "--show-fixes"]
    - id: nbqa-ruff-format
```
Running the hooks works as expected, but when I run 
`pre-commit autoupdate`
I get
```
[https://github.com/nbQA-dev/nbQA] Cannot update because the update target is missing these hooks: nbqa-ruff-check, nbqa-ruff-format
```

Additional details,
OS:
`Arch Linux`
Virtualenv management:
`pipenv, version 2024.0.1`
