### ISSUE TITLE
Feature Request: Support for gitleaks (or trufflehog)

### ISSUE THREAD

**Issue by danielsparing** [nbQA-dev/nbQA#885]
The tools [gitleaks](https://github.com/gitleaks/gitleaks) and [trufflehog](https://github.com/trufflesecurity/trufflehog) can catch secret keys before they're checked in in git, but they don't get triggered by secrets in notebooks.

Theoretically it would be a perfect fit for nbQA to also run (one of) these tools, once the notebooks are already converted to `py` files.

The only issue I can expect is that you don't install `gitleaks` with `pip` but would typically use with a container.

Related issue on the `gitleaks`-side, missing notebook support: https://github.com/gitleaks/gitleaks/issues/914

**Comment by MarcoGorelli** [comment]
hi - sure, open to this if someone submits a pr and it's simple and easy to understand

**Comment by danielsparing** [comment]
I almost made it work:
- [install](https://github.com/gitleaks/gitleaks?tab=readme-ov-file#installing) `gitleaks` on your system (such as `brew install gitleaks` on macOS)
- Then I can successfully run:

```bash
% nbqa "gitleaks dir" --nbqa-shell test_with_secret.ipynb                      

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

2:49PM INF scanned ~268 bytes (268 bytes) in 2.94ms
2:49PM WRN leaks found: 1
```

The thing is, as you see above, I had to use `"gitleaks dir"` as gitleaks it not called as `gitleaks notebook.ipynb` but e.g. `gitleaks dir notebook.ipynb`. (not sure if the quoting as above is the right way, that might the the missing piece)

But then when I am actually trying to introduce it as a custom hook, as follows:

```yaml
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa
        name: nbqa gitleaks
        entry: nbqa "gitleaks dir"
        args: ["--nbqa-shell"]
```

The hook hangs indefinitely.

Any tips? :)
